// +build !ignore_autogenerated

/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by conversion-gen. Do not edit it manually!

package v1alpha1

import (
	authz "github.com/joshvanl/k8s-subject-access-delegation/pkg/apis/authz"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	unsafe "unsafe"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedConversionFuncs(
		Convert_v1alpha1_SubjectAccessDelegation_To_authz_SubjectAccessDelegation,
		Convert_authz_SubjectAccessDelegation_To_v1alpha1_SubjectAccessDelegation,
		Convert_v1alpha1_SubjectAccessDelegationList_To_authz_SubjectAccessDelegationList,
		Convert_authz_SubjectAccessDelegationList_To_v1alpha1_SubjectAccessDelegationList,
		Convert_v1alpha1_SubjectAccessDelegationSpec_To_authz_SubjectAccessDelegationSpec,
		Convert_authz_SubjectAccessDelegationSpec_To_v1alpha1_SubjectAccessDelegationSpec,
		Convert_v1alpha1_SubjectAccessDelegationStatus_To_authz_SubjectAccessDelegationStatus,
		Convert_authz_SubjectAccessDelegationStatus_To_v1alpha1_SubjectAccessDelegationStatus,
	)
}

func autoConvert_v1alpha1_SubjectAccessDelegation_To_authz_SubjectAccessDelegation(in *SubjectAccessDelegation, out *authz.SubjectAccessDelegation, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_SubjectAccessDelegationSpec_To_authz_SubjectAccessDelegationSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_SubjectAccessDelegationStatus_To_authz_SubjectAccessDelegationStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_SubjectAccessDelegation_To_authz_SubjectAccessDelegation is an autogenerated conversion function.
func Convert_v1alpha1_SubjectAccessDelegation_To_authz_SubjectAccessDelegation(in *SubjectAccessDelegation, out *authz.SubjectAccessDelegation, s conversion.Scope) error {
	return autoConvert_v1alpha1_SubjectAccessDelegation_To_authz_SubjectAccessDelegation(in, out, s)
}

func autoConvert_authz_SubjectAccessDelegation_To_v1alpha1_SubjectAccessDelegation(in *authz.SubjectAccessDelegation, out *SubjectAccessDelegation, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_authz_SubjectAccessDelegationSpec_To_v1alpha1_SubjectAccessDelegationSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_authz_SubjectAccessDelegationStatus_To_v1alpha1_SubjectAccessDelegationStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_authz_SubjectAccessDelegation_To_v1alpha1_SubjectAccessDelegation is an autogenerated conversion function.
func Convert_authz_SubjectAccessDelegation_To_v1alpha1_SubjectAccessDelegation(in *authz.SubjectAccessDelegation, out *SubjectAccessDelegation, s conversion.Scope) error {
	return autoConvert_authz_SubjectAccessDelegation_To_v1alpha1_SubjectAccessDelegation(in, out, s)
}

func autoConvert_v1alpha1_SubjectAccessDelegationList_To_authz_SubjectAccessDelegationList(in *SubjectAccessDelegationList, out *authz.SubjectAccessDelegationList, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Items = *(*[]authz.SubjectAccessDelegation)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_SubjectAccessDelegationList_To_authz_SubjectAccessDelegationList is an autogenerated conversion function.
func Convert_v1alpha1_SubjectAccessDelegationList_To_authz_SubjectAccessDelegationList(in *SubjectAccessDelegationList, out *authz.SubjectAccessDelegationList, s conversion.Scope) error {
	return autoConvert_v1alpha1_SubjectAccessDelegationList_To_authz_SubjectAccessDelegationList(in, out, s)
}

func autoConvert_authz_SubjectAccessDelegationList_To_v1alpha1_SubjectAccessDelegationList(in *authz.SubjectAccessDelegationList, out *SubjectAccessDelegationList, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if in.Items == nil {
		out.Items = make([]SubjectAccessDelegation, 0)
	} else {
		out.Items = *(*[]SubjectAccessDelegation)(unsafe.Pointer(&in.Items))
	}
	return nil
}

// Convert_authz_SubjectAccessDelegationList_To_v1alpha1_SubjectAccessDelegationList is an autogenerated conversion function.
func Convert_authz_SubjectAccessDelegationList_To_v1alpha1_SubjectAccessDelegationList(in *authz.SubjectAccessDelegationList, out *SubjectAccessDelegationList, s conversion.Scope) error {
	return autoConvert_authz_SubjectAccessDelegationList_To_v1alpha1_SubjectAccessDelegationList(in, out, s)
}

func autoConvert_v1alpha1_SubjectAccessDelegationSpec_To_authz_SubjectAccessDelegationSpec(in *SubjectAccessDelegationSpec, out *authz.SubjectAccessDelegationSpec, s conversion.Scope) error {
	out.User = in.User
	out.Duration = in.Duration
	out.SomeStuff = in.SomeStuff
	return nil
}

// Convert_v1alpha1_SubjectAccessDelegationSpec_To_authz_SubjectAccessDelegationSpec is an autogenerated conversion function.
func Convert_v1alpha1_SubjectAccessDelegationSpec_To_authz_SubjectAccessDelegationSpec(in *SubjectAccessDelegationSpec, out *authz.SubjectAccessDelegationSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_SubjectAccessDelegationSpec_To_authz_SubjectAccessDelegationSpec(in, out, s)
}

func autoConvert_authz_SubjectAccessDelegationSpec_To_v1alpha1_SubjectAccessDelegationSpec(in *authz.SubjectAccessDelegationSpec, out *SubjectAccessDelegationSpec, s conversion.Scope) error {
	out.User = in.User
	out.Duration = in.Duration
	out.SomeStuff = in.SomeStuff
	return nil
}

// Convert_authz_SubjectAccessDelegationSpec_To_v1alpha1_SubjectAccessDelegationSpec is an autogenerated conversion function.
func Convert_authz_SubjectAccessDelegationSpec_To_v1alpha1_SubjectAccessDelegationSpec(in *authz.SubjectAccessDelegationSpec, out *SubjectAccessDelegationSpec, s conversion.Scope) error {
	return autoConvert_authz_SubjectAccessDelegationSpec_To_v1alpha1_SubjectAccessDelegationSpec(in, out, s)
}

func autoConvert_v1alpha1_SubjectAccessDelegationStatus_To_authz_SubjectAccessDelegationStatus(in *SubjectAccessDelegationStatus, out *authz.SubjectAccessDelegationStatus, s conversion.Scope) error {
	out.Processed = in.Processed
	return nil
}

// Convert_v1alpha1_SubjectAccessDelegationStatus_To_authz_SubjectAccessDelegationStatus is an autogenerated conversion function.
func Convert_v1alpha1_SubjectAccessDelegationStatus_To_authz_SubjectAccessDelegationStatus(in *SubjectAccessDelegationStatus, out *authz.SubjectAccessDelegationStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_SubjectAccessDelegationStatus_To_authz_SubjectAccessDelegationStatus(in, out, s)
}

func autoConvert_authz_SubjectAccessDelegationStatus_To_v1alpha1_SubjectAccessDelegationStatus(in *authz.SubjectAccessDelegationStatus, out *SubjectAccessDelegationStatus, s conversion.Scope) error {
	out.Processed = in.Processed
	return nil
}

// Convert_authz_SubjectAccessDelegationStatus_To_v1alpha1_SubjectAccessDelegationStatus is an autogenerated conversion function.
func Convert_authz_SubjectAccessDelegationStatus_To_v1alpha1_SubjectAccessDelegationStatus(in *authz.SubjectAccessDelegationStatus, out *SubjectAccessDelegationStatus, s conversion.Scope) error {
	return autoConvert_authz_SubjectAccessDelegationStatus_To_v1alpha1_SubjectAccessDelegationStatus(in, out, s)
}
