/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package v1alpha1

import (
	authz_v1alpha1 "github.com/joshvanl/k8s-subject-access-delegation/pkg/apis/authz/v1alpha1"
	versioned "github.com/joshvanl/k8s-subject-access-delegation/pkg/client/clientset/versioned"
	internalinterfaces "github.com/joshvanl/k8s-subject-access-delegation/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/joshvanl/k8s-subject-access-delegation/pkg/client/listers/authz/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// SubjectAccessDelegationInformer provides access to a shared informer and lister for
// SubjectAccessDelegations.
type SubjectAccessDelegationInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.SubjectAccessDelegationLister
}

type subjectAccessDelegationInformer struct {
	factory internalinterfaces.SharedInformerFactory
}

// NewSubjectAccessDelegationInformer constructs a new informer for SubjectAccessDelegation type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewSubjectAccessDelegationInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				return client.AuthzV1alpha1().SubjectAccessDelegations(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				return client.AuthzV1alpha1().SubjectAccessDelegations(namespace).Watch(options)
			},
		},
		&authz_v1alpha1.SubjectAccessDelegation{},
		resyncPeriod,
		indexers,
	)
}

func defaultSubjectAccessDelegationInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewSubjectAccessDelegationInformer(client, v1.NamespaceAll, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc})
}

func (f *subjectAccessDelegationInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&authz_v1alpha1.SubjectAccessDelegation{}, defaultSubjectAccessDelegationInformer)
}

func (f *subjectAccessDelegationInformer) Lister() v1alpha1.SubjectAccessDelegationLister {
	return v1alpha1.NewSubjectAccessDelegationLister(f.Informer().GetIndexer())
}
