apiVersion: authz.sad/v1alpha1
kind: SubjectAccessDelegation
metadata:
  name: test-group
  namespace: default
spec:
  repeat: 1
  originSubject:
    kind: ServiceAccount
    name: test-sa
  destinationSubjects:
  - kind: Group
    name: test-group1
  triggers:
  - kind: AddPod
    value: "*"
  deletionTriggers:
  - kind: Time
    value: 5s
