apiVersion: authz.k8s.io/v1alpha1
kind: SubjectAccessDelegation
metadata:
  name: test-sad
spec:
  duration: 10
  repeat: 3
  namespace: default
  originSubject:
    kind: Role
    name: pod-reader
  destinationSubject:
    kind: ServiceAccount
    name: test-sa
---
apiVersion: authz.k8s.io/v1alpha1
kind: SubjectAccessDelegation
metadata:
  name: test-sad2
spec:
  duration: 6
  repeat: 3
  namespace: default
  originSubject:
    kind: Role
    name: pod-logs-reader
  destinationSubject:
    kind: ServiceAccount
    name: test-sa
