apiVersion: authz.k8s.io/v1alpha1
kind: SubjectAccessDelegation
metadata:
  name: test-sad
spec:
  duration: 30
  repeat: 3
  originSubject:
    kind: Role
    name: pod-reader
  destinationSubject:
    kind: ServiceAccount
    name: test-sa
    namespace: default
