apiVersion: authz.k8s.io/v1alpha1
kind: SubjectAccessDelegation
metadata:
  name: test-sad
  namespace: default
spec:
  repeat: 40
  deletionTime: 3s
  originSubject:
    kind: Role
    name: pod-reader
  destinationSubject:
    kind: ServiceAccount
    name: test-sa
  destinationSubjects:
  - kind: ServiceAccount
    name: test-sa
  triggers:
  - kind: Time
    value: 3s
