apiVersion: authz.sad/v1alpha1
kind: SubjectAccessDelegation
metadata:
  name: stress
  namespace: default
spec:
  repeat: 1
  originSubject:
    kind: ServiceAccount
    name: origin-service-account
  destinationSubjects:
  - kind: User
    name: user
  triggers:
  - kind: Time
    value: now
  deletionTriggers:
  - kind: Time
    value: now
