apiVersion: authz.k8s.io/v1alpha1
kind: SubjectAccessDelegation
metadata:
  name: test-pod-add
  namespace: default
spec:
  repeat: 1
  namespace: default
  deletionTime: 3s
  originSubject:
    kind: Role
    name: pod-reader
  destinationSubjects:
  - kind: ServiceAccount
    name: test-sa
  triggers:
  - kind: AddPod
    value: nginx
---
apiVersion: authz.k8s.io/v1alpha1
kind: SubjectAccessDelegation
metadata:
  name: test-pod-del
  namespace: default
spec:
  repeat: 1
  namespace: default
  deletionTime: 3s
  originSubject:
    kind: Role
    name: pod-reader
  destinationSubjects:
  - kind: ServiceAccount
    name: test-sa2
  triggers:
  - kind: DelPod
    value: nginx
