apiVersion: authz.k8s.io/v1alpha1
kind: SubjectAccessDelegation
metadata:
  name: test-delegation
  namespace: default
spec:
  duration: 4
  repeat: 1
  namespace: default
  originSubject:
    kind: Role
    name: pod-reader
  destinationSubjects:
  - kind: ServiceAccount
    name: test-sa
