apiVersion: authz.k8s.io/v1alpha1
kind: SubjectAccessDelegation
metadata:
  name: test-delegation
  namespace: default
spec:
  repeat: 1
  namespace: default
  deletionTime: 10s
  originSubject:
    kind: Role
    name: pod-reader
  destinationSubjects:
  - kind: ServiceAccount
    name: test-sa
  triggers:
  - kind: Time
    value: 10s
