apiVersion: authz.k8s.io/v1alpha1
kind: SubjectAccessDelegation
metadata:
  name: test-sad
spec:
  duration: 30
  repeat: 3
  namespace: default
  originSubject:
    kind: User
    name: user-a
  destinationSubject:
    kind: ServiceAccount
    name: default
