apiVersion: authz.sad/v1alpha1
kind: SubjectAccessDelegation
metadata:
  name: test-delegation
  namespace: default
spec:
  repeat: 3
  deletionTime: 3s
  originSubject:
    kind: Role
    name: pod-reader
  destinationSubjects:
  - kind: ServiceAccount
    name: test-sa
  triggers:
  - kind: Time
    value: 1s
  - kind: Time
    value: 3s
